Sprint 12
RdDevi1/ImageFeed pull request #5
Opened 2023-02-03 15:10 UTC by RdDevi1

2023-02-04 11:40 UTC, IBDesignable requested changes

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +    }
лучше вынести подобный код в отдельный сервис. Не дело его во вью контроллере статиком держать :)

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Constants.swift
> - enum ConstantsUnsplash {
было лучше! почему избавился?

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Helpers/Date extension.swift
> +//  Date extension.swift
давай запомним, что пробелы в названиях файлов не лучшая затея и везде это поправим

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Helpers/Date extension.swift
> +        let dateFormatter = ISO8601DateFormatter()
этот форматтер тоже надо сделать статичным, как в коде выше.

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Helpers/UI extension.swift
> +}
глобальные функции не принято делать, давай сделаем в расширении тоже самое

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        tableView.reloadRows(at: [indexPath], with: .automatic)
то что сейчас происходит в таблице может вызвать подергивание глаза :) слишком много прыгающих анимаций, давай эту штуку уберем, думаю станет лучше

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Presentations/ProfileViewController.swift
> +        oAuth2TokenStorage.bearerToken = nil
при получении nil ничего не происходит, у тебя там не хватает одной ветви для обработки ситуации

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Presentations/SingleImageViewController.swift
> +    }
очень много одинакого кода, может попробуешь написать презентер, как в предыдущем приложении?

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +    private let formatter = ISO8601DateFormatter()
не используется

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +        let nextPage = lastLoadedPage == nil ? 1 : lastLoadedPage! + 1
давай разучимся писать такой код :) никакие форсанврапы не пойдут тебе на пользу в тестовых заданиях на позицию, лучше так:

```
if let lastLoadedPage { 
nextPage = lastLoadedPage +1 
} else {
nextPage = 1
}
```

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +                    )
можно написать функцию в приватном расширении convertToViewModel() 
и тогда код можно переписать в функциональном стиле photoResult.map { $0.convertToViewModel) без циклов :) 

и добавить в конец массива новый подмассив

2023-02-04 11:40 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
> +            }
пропущено удаление removeObject

2023-02-04 18:01 UTC, RdDevi1 commented on ImageFeed/Constants.swift
> - enum ConstantsUnsplash {
была какая-то ошибка, приходилось перепроверять сервисы где использовались эти константы и как то и интуитивно показалось проще/быстрее получать доступ к ним напрямую, а не через enum.  Вернусь к исходному варианту))

2023-02-04 18:53 UTC, RdDevi1 commented on ImageFeed/Helpers/Date extension.swift
> +        let dateFormatter = ISO8601DateFormatter()
а тут если ставить static var dateTimeString, то ошибка на self: Cannot convert value of type 'Date.Type' to expected argument type 'Date'. И дальше при корректировке кода в ячейку устанавливается текущая дата...
Если dateFormatter (объявленный выше) уже статичный и существует, то мы просто используем его в dateTimeString, что не должно вести к "утяжелению" операции?

2023-02-04 19:00 UTC, RdDevi1 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        tableView.reloadRows(at: [indexPath], with: .automatic)
согласен))

2023-02-04 19:03 UTC, RdDevi1 commented on ImageFeed/Services/ImagesListService.swift
> +        let nextPage = lastLoadedPage == nil ? 1 : lastLoadedPage! + 1
вначале пробовал использовать тернарник из учебника, но как то с ним не срослось, чуть чуть поправил) скорректирую на предложенный вариант)

2023-02-04 19:08 UTC, RdDevi1 commented on ImageFeed/Services/OAuth2TokenStorage.swift
> +            }
а почему необходимо удалять, а не просто присваивать новое значение переменой?)

2023-02-04 20:59 UTC, RdDevi1 commented on ImageFeed/Presentations/SingleImageViewController.swift
> +    }
попробую как функцию для UIVC сделать в расширении

2023-02-05 12:03 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
> +            }
Не уверена, что есть такая перегрузка с установкой значения в nil. Но если есть – то используй ее. 

Здесь же у тебя ошибка в том, что когад сюда нил придет, условие if let не выполнится, и ты вообще ничего не сделаешь с новым значением.

2023-02-06 17:13 UTC, RdDevi1 commented on ImageFeed/Services/ImagesListService.swift
> +                    )
это учту, дополню в ходе следующего спринта или на каникулах))

2023-02-06 19:07 UTC, IBDesignable commented on ImageFeed/Helpers/Date extension.swift
> +        let dateFormatter = ISO8601DateFormatter()
> форматтер тоже надо сделать статичным

Вот так:
`private static let iso8601Formatter = ISO8601DateFormatter()`

Тогда твоя функция будет выглядеть так: 
```
 static func convertStringToDate(_ string: String) -> Date? {
        return iso8601Formatter.date(from: string)
 }
```

2023-02-08 16:12 UTC, IBDesignable commented on ImageFeed/Helpers/Date+extension.swift
> +
👍🏻

2023-02-08 16:14 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
>              }
```swift
            if let bearerToken = newValue { // если newValue это nil, то условие не выполнится, значение не будет удалено, не будет добавлено
                keychainWrapper.removeObject(forKey: Keys.bearerToken.rawValue)
                keychainWrapper.set(bearerToken, forKey: Keys.bearerToken.rawValue)
            }
```

Я ожидала вот такого исправления:
```suggestion
            if let bearerToken = newValue {
                keychainWrapper.set(bearerToken, forKey: Keys.bearerToken.rawValue)
            } else {
                keychainWrapper.removeObject(forKey: Keys.bearerToken.rawValue)
            }
```

2023-02-08 16:26 UTC, RdDevi1 commented on ImageFeed/Services/OAuth2TokenStorage.swift
>              }
а, это условия я не учел) спасибо)

2023-02-08 16:28 UTC, RdDevi1 commented
Александра, ревью максимально быстрое) спасибо за помощь и подробное описание ошибок)

2023-02-08 17:39 UTC, merged